version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:

      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dndcharlist
  registration:
    image: 'dnd-char-list-registration'
    build:
      context: .
    ports:
      - "8090:8080"
    container_name: registration
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dndcharlist
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update